### ISSUE TITLE
黄色方框，粗细为5， 大小为80×80，中间留透明

### ISSUE THREAD

**Issue by umiringo** [umiringo/Dunkleosteus#28]

**Comment by crystaleos** [comment]
#closed

王安梦

网易LOFTER
邀您一同发现和记录生活之美

Mobile：13208018402
WeChat：crystaleos
QQ：386245615
Email：crystaleos@outlook.com

---

发件人: umiringo notifications@github.com
发送时间: 2016年6月28日 10:37:52
收件人: umiringo/Dunkleosteus
主题: [umiringo/Dunkleosteus] 黄色方框，粗细为5， 大小为80×80 (#28)

―
